name: Accept invites
on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * *'  # This schedule is set to run every hour at 42 minutes past the hour

jobs:
  accept-invites:
    runs-on: ubuntu-22.04

    steps:
      # @see https://docs.github.com/en/rest/collaborators/invitations?apiVersion=2022-11-28
      - name: Accept all repository invites
        uses: kbrashears5/github-action-auto-accept-collabs@v2.0.0
        with:
          TOKEN: ${{ secrets.IXDF_BOT_PAT_TO_ACCEPT_INVITES }}